# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/biozero/simulated-adversary"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/biozero/services/zeroresponder"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/biozero/services/uploader-cli"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/biozero/services/upload-api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/biozero/services/enclave-runner"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/biozero/services/results-api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/biozero/ui"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/biozero/services/zeroresponder"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/biozero/services/upload-api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/biozero/services/enclave-runner"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/biozero/services/results-api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "/biozero/infra/compose"
    schedule:
      interval: "weekly"
